# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS
BRAINTREE_MERCHANT_ID: 'wvkntq6743dfndwf'
BRAINTREE_PUBLIC_KEY: 'r8m56d63k545d5hj'
BRAINTREE_PRIVATE_KEY: '6f95b5294bc59a072b520c450fdaa856'